// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _PyCFrame {
 *     struct _PyInterpreterFrame *current_frame;
 *     struct _PyCFrame *previous;
 * }
 * }
 */
public class _PyCFrame {

    _PyCFrame() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_POINTER.withName("current_frame"),
        Python_h.C_POINTER.withName("previous")
    ).withName("_PyCFrame");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout current_frame$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("current_frame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct _PyInterpreterFrame *current_frame
     * }
     */
    public static final AddressLayout current_frame$layout() {
        return current_frame$LAYOUT;
    }

    private static final long current_frame$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct _PyInterpreterFrame *current_frame
     * }
     */
    public static final long current_frame$offset() {
        return current_frame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct _PyInterpreterFrame *current_frame
     * }
     */
    public static MemorySegment current_frame(MemorySegment struct) {
        return struct.get(current_frame$LAYOUT, current_frame$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct _PyInterpreterFrame *current_frame
     * }
     */
    public static void current_frame(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(current_frame$LAYOUT, current_frame$OFFSET, fieldValue);
    }

    private static final AddressLayout previous$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("previous"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct _PyCFrame *previous
     * }
     */
    public static final AddressLayout previous$layout() {
        return previous$LAYOUT;
    }

    private static final long previous$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct _PyCFrame *previous
     * }
     */
    public static final long previous$offset() {
        return previous$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct _PyCFrame *previous
     * }
     */
    public static MemorySegment previous(MemorySegment struct) {
        return struct.get(previous$LAYOUT, previous$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct _PyCFrame *previous
     * }
     */
    public static void previous(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(previous$LAYOUT, previous$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

