// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef _Lldiv_t imaxdiv_t
 * }
 */
public class imaxdiv_t extends _Lldiv_t$4 {

    imaxdiv_t() {
        // Should not be called directly
    }
}

