// Generated by jextract

package io.github.gaming32.pyjabr.lowlevel.cpython;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _object {
 *     union {
 *         Py_ssize_t ob_refcnt;
 *         uint32_t ob_refcnt_split[2];
 *     };
 *     PyTypeObject *ob_type;
 * } PyLongObject
 * }
 */
public class PyLongObject extends _object {

    PyLongObject() {
        // Should not be called directly
    }
}

