from typing import Any

from _java_init import FakeJavaObject, FakeJavaStaticMethod, _JavaAttributeNotFoundType


def find_class(name: str) -> int | None: ...

def remove_class(id: int) -> None: ...

def find_class_attribute(
    owner_name: str,
    owner_id: int,
    name: str
) -> FakeJavaStaticMethod | int | _JavaAttributeNotFoundType: ...

def invoke_static_method(method_id: int, args: tuple[Any, ...]) -> Any: ...

def get_static_field(field_id: int) -> Any: ...

def set_static_field(field_id: int, value: Any) -> None: ...

def remove_static_method(id: int) -> None: ...

def remove_static_field(id: int) -> None: ...

def reflect_class_object(id: int) -> FakeJavaObject: ...

def remove_object(id: int) -> None: ...

def to_string(id: int) -> str: ...

def hash_code(id: int) -> int: ...

def identity_string(id: int) -> str: ...

def identity_hash(id: int) -> int: ...
