from typing import Any

from java_api import FakeJavaObject, FakeJavaMethod, _JavaAttributeNotFoundType


def find_class(name: str) -> int | None: ...

def remove_class(class_id: int) -> None: ...

def find_class_attribute(
    owner_name: str,
    owner_id: int,
    name: str,
    is_static: bool
) -> FakeJavaMethod | int | _JavaAttributeNotFoundType: ...

def invoke_static_method(method_id: int, args: tuple[Any, ...]) -> Any: ...

def get_static_field(field_id: int) -> Any: ...

def set_static_field(field_id: int, value: Any) -> None: ...

def remove_static_method(method_id: int) -> None: ...

def remove_static_field(field_id: int) -> None: ...

def reflect_class_object(class_id: int) -> FakeJavaObject: ...

def remove_object(object_id: int) -> None: ...

def to_string(object_id: int) -> str: ...

def hash_code(object_id: int) -> int: ...

def identity_string(object_id: int) -> str: ...

def identity_hash(object_id: int) -> int: ...
