// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _py_trashcan {
 *     int delete_nesting;
 *     PyObject *delete_later;
 * }
 * }
 */
public class _py_trashcan {

    _py_trashcan() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_INT.withName("delete_nesting"),
        MemoryLayout.paddingLayout(4),
        Python_h.C_POINTER.withName("delete_later")
    ).withName("_py_trashcan");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt delete_nesting$LAYOUT = (OfInt)$LAYOUT.select(groupElement("delete_nesting"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int delete_nesting
     * }
     */
    public static final OfInt delete_nesting$layout() {
        return delete_nesting$LAYOUT;
    }

    private static final long delete_nesting$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int delete_nesting
     * }
     */
    public static final long delete_nesting$offset() {
        return delete_nesting$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int delete_nesting
     * }
     */
    public static int delete_nesting(MemorySegment struct) {
        return struct.get(delete_nesting$LAYOUT, delete_nesting$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int delete_nesting
     * }
     */
    public static void delete_nesting(MemorySegment struct, int fieldValue) {
        struct.set(delete_nesting$LAYOUT, delete_nesting$OFFSET, fieldValue);
    }

    private static final AddressLayout delete_later$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("delete_later"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *delete_later
     * }
     */
    public static final AddressLayout delete_later$layout() {
        return delete_later$LAYOUT;
    }

    private static final long delete_later$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *delete_later
     * }
     */
    public static final long delete_later$offset() {
        return delete_later$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *delete_later
     * }
     */
    public static MemorySegment delete_later(MemorySegment struct) {
        return struct.get(delete_later$LAYOUT, delete_later$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *delete_later
     * }
     */
    public static void delete_later(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(delete_later$LAYOUT, delete_later$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

