name: Run tests
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 22
          distribution: zulu
          cache: gradle
      - name: Install libpython3.12-dev
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt install libpython3.12-dev
      - name: Install Python 3.12
        if: matrix.os == 'windows-latest'
        run: |
          curl -o python-installer.exe https://www.python.org/ftp/python/3.12.4/python-3.12.4-amd64.exe
          python-installer.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0
      - name: Build with Gradle
        run: ./gradlew test
