name: Gradle build
on: [push, pull_request, workflow_dispatch]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 22
          distribution: zulu
          cache: gradle
      - name: Install libpython
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt install libpython3.12-dev
      - name: Build with Gradle
        run: ./gradlew test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml
