name: Run tests
on: [push, pull_request, workflow_dispatch]

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 22
          distribution: zulu
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew test --stacktrace
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml
